"""SAPPO V1 anchor-loss correctness tests.

Required by artifacts/strategic_demand/STRATEGY_ANCHORED_PPO_V1_FROZEN.json to
pass BEFORE the +500k continuation consumes its first environment step.

Covered here (1, 2, 4, 5 of the required list):
  1. exact-action preference   -- loss is lower when the teacher action is likely
  2. gradient direction        -- one anchor step raises P(teacher action)
  4. action encoding round-trip-- demo actions decode to the exact (macro,
                                  waypoint) layout the actor expects, no silent
                                  remapping
  5. observation compatibility -- stored demo observations match the policy's
                                  expected input keys, dtypes and shapes

Tests 3 (lambda=0 reproduces the pre-SAPPO update path) and 6 (measured anchor:
PPO minibatch ratio == 0.25) require the trainer integration and live with it,
because both are statements about the update loop rather than about the loss.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest
import torch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from rl.custom_ppo.distributions import ActionHead, MultiHeadActionDistribution  # noqa: E402
from rl.custom_ppo.strategy_anchor import (  # noqa: E402
    action_log_prob, anchor_loss, teacher_agreement,
)

DEMO_DIR = ROOT / "artifacts/strategic_demand/sappo_demonstrations"


class _StubModel:
    """Minimal stand-in exposing the real public contract: get_distribution()."""

    def __init__(self, logits: list[torch.Tensor]):
        self._logits = logits

    def get_distribution(self, obs, *, z_idx=None):
        return MultiHeadActionDistribution([ActionHead(h) for h in self._logits])


def test_1_exact_action_preference():
    """Anchor loss must be lower when the teacher action carries more mass."""
    teacher = torch.tensor([[0, 3]])
    favourable = [torch.tensor([[5.0, 0.0, 0.0]]), torch.tensor([[0.0] * 3 + [5.0]])]
    unfavourable = [torch.tensor([[0.0, 5.0, 0.0]]), torch.tensor([[5.0] + [0.0] * 3])]

    lo = anchor_loss(_StubModel(favourable), {}, teacher)
    hi = anchor_loss(_StubModel(unfavourable), {}, teacher)
    assert lo < hi, f"expected lower loss when teacher action is likely: {lo} vs {hi}"
    assert lo > 0, "negative log-prob must be positive"


def test_2_gradient_raises_teacher_action_probability():
    """One optimizer step on the anchor loss must increase P(teacher action)."""
    logits = [torch.zeros(1, 3, requires_grad=True),
              torch.zeros(1, 4, requires_grad=True)]
    teacher = torch.tensor([[2, 1]])
    model = _StubModel(logits)

    before = [l.detach().softmax(-1)[0, a].item()
              for l, a in zip(logits, teacher[0].tolist())]
    opt = torch.optim.SGD(logits, lr=1.0)
    opt.zero_grad()
    anchor_loss(model, {}, teacher).backward()
    opt.step()
    after = [l.detach().softmax(-1)[0, a].item()
             for l, a in zip(logits, teacher[0].tolist())]

    for b, a_, h in zip(before, after, range(len(logits))):
        assert a_ > b, f"head {h}: P(teacher) did not increase ({b} -> {a_})"


def test_2b_decision_mask_zeroes_locked_agents():
    """A locked agent must contribute no gradient."""
    logits = [torch.zeros(1, 3, requires_grad=True),  # agent 0 macro
              torch.zeros(1, 4, requires_grad=True),  # agent 0 target
              torch.zeros(1, 3, requires_grad=True),  # agent 1 macro
              torch.zeros(1, 4, requires_grad=True)]  # agent 1 target
    teacher = torch.tensor([[[1, 2], [0, 3]]])          # (batch, agents, heads)
    mask = torch.tensor([[True, False]])                # agent 1 is locked
    anchor_loss(_StubModel(logits), {}, teacher, mask).backward()

    assert logits[0].grad.abs().sum() > 0, "unlocked agent must receive gradient"
    assert logits[2].grad.abs().sum() == 0, "LOCKED agent must receive no gradient"
    assert logits[3].grad.abs().sum() == 0, "LOCKED agent must receive no gradient"


def test_4_action_encoding_round_trip():
    """Demo actions must match the policy head layout exactly, or raise."""
    logits = [torch.zeros(2, 3), torch.zeros(2, 4)]
    ok = torch.tensor([[1, 2], [0, 3]])
    action_log_prob(_StubModel(logits), {}, ok)          # must not raise

    with pytest.raises(ValueError, match="action encoding mismatch"):
        action_log_prob(_StubModel(logits), {}, torch.zeros(2, 3, dtype=torch.long))

    with pytest.raises(ValueError, match="out of range"):
        action_log_prob(_StubModel(logits), {}, torch.tensor([[9, 0], [0, 0]]))


def test_4b_agent_major_flattening_matches_collection():
    """(batch, n_agents, heads_per_agent) must flatten agent-major.

    The demonstrations were generated by stepping the env with
    act.reshape(-1), so any other flattening here would transpose macro and
    waypoint labels silently.
    """
    a = torch.tensor([[[10, 11], [20, 21]]])
    assert a.reshape(1, -1).tolist() == [[10, 11, 20, 21]], "agent-major order broken"


@pytest.mark.skipif(not (DEMO_DIR / "anchor_A_train.npz").is_file(),
                    reason="demonstration dataset not collected yet")
def test_5_observation_compatibility():
    """Stored demo observations must carry the keys/shapes the policy consumes."""
    d = np.load(DEMO_DIR / "anchor_A_train.npz")
    obs_keys = {k[len("obs_"):] for k in d.files if k.startswith("obs_")}
    assert {"grid", "vec", "agent_mask", "mask"} <= obs_keys, obs_keys

    n = d["actions"].shape[0]
    assert d["obs_grid"].shape[0] == n, "obs/action row count mismatch"
    assert d["decision_mask"].shape[0] == n, "mask/action row count mismatch"
    assert d["actions"].shape[1:] == (2, 2), d["actions"].shape
    assert d["obs_grid"].dtype == np.float32
    assert d["obs_grid"].shape[1:] == (2, 7, 20, 20), d["obs_grid"].shape
    assert d["decision_mask"].any(), "no decision points recorded"


@pytest.mark.skipif(not (DEMO_DIR / "anchor_A_train.npz").is_file(),
                    reason="demonstration dataset not collected yet")
def test_5b_teacher_agreement_is_bounded():
    d = np.load(DEMO_DIR / "anchor_A_train.npz")
    acts = torch.from_numpy(d["actions"][:4]).long()
    mask = torch.from_numpy(d["decision_mask"][:4]).bool()
    logits = [torch.zeros(4, 5), torch.zeros(4, 50),
              torch.zeros(4, 5), torch.zeros(4, 50)]
    agr = teacher_agreement(_StubModel(logits), {}, acts, mask)
    assert 0.0 <= agr <= 1.0, agr


# ---------------------------------------------------------------------------
# Tests 3 and 6 -- statements about the update loop, and the stale-gradient
# launch blocker. All are launch blockers for the +500k continuation.
# ---------------------------------------------------------------------------

class _StubDataset:
    def __init__(self, actions, mask):
        self._a, self._m = actions, mask

    def sample(self, device="cpu"):
        return {}, self._a, self._m


class _StubOptim:
    """Records whether it was stepped, so 'disabled' can be proven inert."""

    def __init__(self, params):
        self.param_groups = [{"params": list(params)}]
        self.n_steps = 0
        self.n_zero_grads = 0

    def zero_grad(self, set_to_none=True):
        self.n_zero_grads += 1
        for p in self.param_groups[0]["params"]:
            p.grad = None if set_to_none else torch.zeros_like(p)

    def step(self):
        self.n_steps += 1
        with torch.no_grad():
            for p in self.param_groups[0]["params"]:
                if p.grad is not None:
                    p -= 0.1 * p.grad


def _runner(logits, actions, mask, lam=0.10, cadence=4):
    from rl.custom_ppo.strategy_anchor import AnchorRunner
    model = _StubModel(logits)
    opt = _StubOptim(logits)
    return AnchorRunner(model, opt, _StubDataset(actions, mask),
                        lambda_anchor=lam, cadence=cadence), opt


def test_3_disabled_is_structurally_absent():
    """Disabled anchoring must not be expressible as lambda=0.

    A nominal zero-loss step can still mutate optimizer state, advance
    counters, or apply weight decay, so 'off' must mean 'no runner'.
    """
    from rl.custom_ppo.strategy_anchor import AnchorRunner
    with pytest.raises(ValueError, match="must not be constructed"):
        AnchorRunner(None, None, None, lambda_anchor=0.0)
    with pytest.raises(ValueError, match="must not be constructed"):
        AnchorRunner(None, None, None, lambda_anchor=-1.0)


def test_3b_no_runner_means_no_optimizer_mutation():
    """With no runner, the PPO path performs zero anchor-driven work."""
    logits = [torch.zeros(1, 3, requires_grad=True),
              torch.zeros(1, 4, requires_grad=True)]
    opt = _StubOptim(logits)
    before = [l.detach().clone() for l in logits]
    runner = None
    for _ in range(16):                      # 16 PPO minibatches, anchoring off
        if runner is not None:               # the integration guard
            runner.note_ppo_minibatch()
    assert opt.n_steps == 0, "optimizer stepped with anchoring disabled"
    assert opt.n_zero_grads == 0, "zero_grad called with anchoring disabled"
    for b, l in zip(before, logits):
        assert torch.equal(b, l.detach()), "parameters changed with anchoring disabled"


def test_6_measured_cadence_is_one_per_four():
    """Count real optimizer steps, not the configured constant."""
    logits = [torch.zeros(1, 3, requires_grad=True),
              torch.zeros(1, 4, requires_grad=True)]
    r, opt = _runner(logits, torch.tensor([[1, 2]]), None)
    for _ in range(16):
        r.note_ppo_minibatch()
    t = r.telemetry()
    assert t["n_ppo_actor_minibatches"] == 16
    assert t["n_anchor_updates"] == 4, t
    assert t["anchor_per_ppo_ratio"] == 0.25, t
    assert t["complete_group_ratio_is_one"] is True
    assert opt.n_steps == 4, "anchor optimizer steps != anchor updates"


def test_6b_partial_group_emits_no_trailing_anchor():
    """The ratio must never be forced on an incomplete group."""
    logits = [torch.zeros(1, 3, requires_grad=True),
              torch.zeros(1, 4, requires_grad=True)]
    r, opt = _runner(logits, torch.tensor([[1, 2]]), None)
    for _ in range(11):                      # 2 complete groups + 3 leftover
        r.note_ppo_minibatch()
    t = r.telemetry()
    assert t["n_anchor_updates"] == 2, t
    assert t["expected_complete_groups"] == 2
    assert t["complete_group_ratio_is_one"] is True
    assert opt.n_steps == 2


def test_stale_gradient_blocker_no_ppo_grads_survive_into_anchor_step():
    """LAUNCH BLOCKER: leftover PPO gradients must not ride into the anchor step.

    Simulates the real hazard: the PPO stepper leaves gradients populated after
    step(), so a huge stale gradient is planted on a parameter the anchor loss
    does NOT touch. If the runner failed to zero first, that stale gradient
    would be applied by the anchor optimizer step while every counter still
    read 0.25.
    """
    anchor_param = torch.zeros(1, 3, requires_grad=True)
    unrelated = torch.zeros(1, 4, requires_grad=True)   # e.g. a critic-only head
    from rl.custom_ppo.strategy_anchor import AnchorRunner

    model = _StubModel([anchor_param, torch.zeros(1, 4)])
    opt = _StubOptim([anchor_param, unrelated])
    r = AnchorRunner(model, opt, _StubDataset(torch.tensor([[1, 2]]), None),
                     lambda_anchor=0.10, cadence=4)

    unrelated.grad = torch.full_like(unrelated, 1000.0)   # stale PPO gradient
    unrelated_before = unrelated.detach().clone()

    for _ in range(4):
        r.note_ppo_minibatch()

    assert r.n_anchor_updates == 1
    assert torch.equal(unrelated.detach(), unrelated_before), (
        "STALE PPO GRADIENT WAS APPLIED during the anchor step -- the "
        "'NLL-only rehearsal' claim would be false")
    assert unrelated.grad is None or float(unrelated.grad.abs().sum()) == 0.0, (
        "anchor step left stale gradients resident")
