"""SAPPO V1 anchor-loss correctness tests.

Required by artifacts/strategic_demand/STRATEGY_ANCHORED_PPO_V1_FROZEN.json to
pass BEFORE the +500k continuation consumes its first environment step.

Covered here (1, 2, 4, 5 of the required list):
  1. exact-action preference   -- loss is lower when the teacher action is likely
  2. gradient direction        -- one anchor step raises P(teacher action)
  4. action encoding round-trip-- demo actions decode to the exact (macro,
                                  waypoint) layout the actor expects, no silent
                                  remapping
  5. observation compatibility -- stored demo observations match the policy's
                                  expected input keys, dtypes and shapes

Tests 3 (lambda=0 reproduces the pre-SAPPO update path) and 6 (measured anchor:
PPO minibatch ratio == 0.25) require the trainer integration and live with it,
because both are statements about the update loop rather than about the loss.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest
import torch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from rl.custom_ppo.distributions import ActionHead, MultiHeadActionDistribution  # noqa: E402
from rl.custom_ppo.strategy_anchor import (  # noqa: E402
    action_log_prob, anchor_loss, teacher_agreement,
)

DEMO_DIR = ROOT / "artifacts/strategic_demand/sappo_demonstrations"


class _StubModel:
    """Minimal stand-in exposing the real public contract: get_distribution()."""

    def __init__(self, logits: list[torch.Tensor]):
        self._logits = logits

    def get_distribution(self, obs, *, z_idx=None):
        return MultiHeadActionDistribution([ActionHead(h) for h in self._logits])


def test_1_exact_action_preference():
    """Anchor loss must be lower when the teacher action carries more mass."""
    teacher = torch.tensor([[0, 3]])
    favourable = [torch.tensor([[5.0, 0.0, 0.0]]), torch.tensor([[0.0] * 3 + [5.0]])]
    unfavourable = [torch.tensor([[0.0, 5.0, 0.0]]), torch.tensor([[5.0] + [0.0] * 3])]

    lo = anchor_loss(_StubModel(favourable), {}, teacher)
    hi = anchor_loss(_StubModel(unfavourable), {}, teacher)
    assert lo < hi, f"expected lower loss when teacher action is likely: {lo} vs {hi}"
    assert lo > 0, "negative log-prob must be positive"


def test_2_gradient_raises_teacher_action_probability():
    """One optimizer step on the anchor loss must increase P(teacher action)."""
    logits = [torch.zeros(1, 3, requires_grad=True),
              torch.zeros(1, 4, requires_grad=True)]
    teacher = torch.tensor([[2, 1]])
    model = _StubModel(logits)

    before = [l.detach().softmax(-1)[0, a].item()
              for l, a in zip(logits, teacher[0].tolist())]
    opt = torch.optim.SGD(logits, lr=1.0)
    opt.zero_grad()
    anchor_loss(model, {}, teacher).backward()
    opt.step()
    after = [l.detach().softmax(-1)[0, a].item()
             for l, a in zip(logits, teacher[0].tolist())]

    for b, a_, h in zip(before, after, range(len(logits))):
        assert a_ > b, f"head {h}: P(teacher) did not increase ({b} -> {a_})"


def test_2b_decision_mask_zeroes_locked_agents():
    """A locked agent must contribute no gradient."""
    logits = [torch.zeros(1, 3, requires_grad=True),  # agent 0 macro
              torch.zeros(1, 4, requires_grad=True),  # agent 0 target
              torch.zeros(1, 3, requires_grad=True),  # agent 1 macro
              torch.zeros(1, 4, requires_grad=True)]  # agent 1 target
    teacher = torch.tensor([[[1, 2], [0, 3]]])          # (batch, agents, heads)
    mask = torch.tensor([[True, False]])                # agent 1 is locked
    anchor_loss(_StubModel(logits), {}, teacher, mask).backward()

    assert logits[0].grad.abs().sum() > 0, "unlocked agent must receive gradient"
    assert logits[2].grad.abs().sum() == 0, "LOCKED agent must receive no gradient"
    assert logits[3].grad.abs().sum() == 0, "LOCKED agent must receive no gradient"


def test_4_action_encoding_round_trip():
    """Demo actions must match the policy head layout exactly, or raise."""
    logits = [torch.zeros(2, 3), torch.zeros(2, 4)]
    ok = torch.tensor([[1, 2], [0, 3]])
    action_log_prob(_StubModel(logits), {}, ok)          # must not raise

    with pytest.raises(ValueError, match="action encoding mismatch"):
        action_log_prob(_StubModel(logits), {}, torch.zeros(2, 3, dtype=torch.long))

    with pytest.raises(ValueError, match="out of range"):
        action_log_prob(_StubModel(logits), {}, torch.tensor([[9, 0], [0, 0]]))


def test_4b_agent_major_flattening_matches_collection():
    """(batch, n_agents, heads_per_agent) must flatten agent-major.

    The demonstrations were generated by stepping the env with
    act.reshape(-1), so any other flattening here would transpose macro and
    waypoint labels silently.
    """
    a = torch.tensor([[[10, 11], [20, 21]]])
    assert a.reshape(1, -1).tolist() == [[10, 11, 20, 21]], "agent-major order broken"


@pytest.mark.skipif(not (DEMO_DIR / "anchor_A_train.npz").is_file(),
                    reason="demonstration dataset not collected yet")
def test_5_observation_compatibility():
    """Stored demo observations must carry the keys/shapes the policy consumes."""
    d = np.load(DEMO_DIR / "anchor_A_train.npz")
    obs_keys = {k[len("obs_"):] for k in d.files if k.startswith("obs_")}
    assert {"grid", "vec", "agent_mask", "mask"} <= obs_keys, obs_keys

    n = d["actions"].shape[0]
    assert d["obs_grid"].shape[0] == n, "obs/action row count mismatch"
    assert d["decision_mask"].shape[0] == n, "mask/action row count mismatch"
    assert d["actions"].shape[1:] == (2, 2), d["actions"].shape
    assert d["obs_grid"].dtype == np.float32
    assert d["obs_grid"].shape[1:] == (2, 7, 20, 20), d["obs_grid"].shape
    assert d["decision_mask"].any(), "no decision points recorded"


@pytest.mark.skipif(not (DEMO_DIR / "anchor_A_train.npz").is_file(),
                    reason="demonstration dataset not collected yet")
def test_5b_teacher_agreement_is_bounded():
    d = np.load(DEMO_DIR / "anchor_A_train.npz")
    acts = torch.from_numpy(d["actions"][:4]).long()
    mask = torch.from_numpy(d["decision_mask"][:4]).bool()
    logits = [torch.zeros(4, 5), torch.zeros(4, 50),
              torch.zeros(4, 5), torch.zeros(4, 50)]
    agr = teacher_agreement(_StubModel(logits), {}, acts, mask)
    assert 0.0 <= agr <= 1.0, agr
