$ErrorActionPreference = 'Continue'
Set-Location 'K:\MultiAgentUAV\AICTFProject'
$env:FOR_DISABLE_CONSOLE_CTRL_HANDLER = '1'
Write-Host '=== TOP50_2V2_NOROLE ==='
& .\.venv\Scripts\python.exe experiments/eval_specialist_crossover_scaled.py --team-size 2 --spec artifacts/strategic_demand/sppo/SYMMETRIC_ROLE_TOP50_DIAGNOSTIC_SPEC.json --post-hoc-ablation-spec artifacts/strategic_demand/sppo/SYMMETRIC_ROLE_TOP50_DIAGNOSTIC_SPEC.json --seed-list artifacts/strategic_demand/sppo/symmetric_role_top50/2v2_ours_top50_seed_ids.json --pi-a-path artifacts/scale_2v2_specialists/pi_A_specialist_2v2_std_entity_repair/ckpts/final_pi_A_specialist_2v2_std_entity_repair.zip --pi-b-path artifacts/scale_2v2_specialists/pi_B_specialist_2v2_std_entity_repair/ckpts/final_pi_B_specialist_2v2_std_entity_repair.zip --label TOP50_2V2_NOROLE --registry-experiment-id STANDARDIZED_2V2_SPLIT_K1_CONFIRMATORY_SPECIALIST_CROSSOVER --device cuda --resume 2> artifacts/strategic_demand/sppo/suite_sharing_std/top50/TOP50_2V2_NOROLE.log.err
Write-Host ('2v2 exit=' + $LASTEXITCODE)
Write-Host '=== TOP50_4V4_NOROLE ==='
& .\.venv\Scripts\python.exe experiments/eval_specialist_crossover_scaled.py --team-size 4 --spec artifacts/strategic_demand/sppo/SYMMETRIC_ROLE_TOP50_DIAGNOSTIC_SPEC.json --post-hoc-ablation-spec artifacts/strategic_demand/sppo/SYMMETRIC_ROLE_TOP50_DIAGNOSTIC_SPEC.json --seed-list artifacts/strategic_demand/sppo/symmetric_role_top50/4v4_ours_top50_seed_ids.json --pi-a-path artifacts/scale_4v4_specialists/pi_A_specialist_4v4_b3_entity_repair/ckpts/final_pi_A_specialist_4v4_b3_entity_repair.zip --pi-b-path artifacts/scale_4v4_specialists/pi_B_specialist_4v4_b3_entity_repair_corrected/ckpts/final_pi_B_specialist_4v4_b3_entity_repair_corrected.zip --label TOP50_4V4_NOROLE --registry-experiment-id DEFEND_ATTACK_SPLIT_POLICY_A_V1_CONFIRMATORY_V1_EVAL --device cuda --resume 2> artifacts/strategic_demand/sppo/suite_sharing_std/top50/TOP50_4V4_NOROLE.log.err
Write-Host ('4v4 exit=' + $LASTEXITCODE)
