from __future__ import annotations


def _build_episode_result_payload(info: dict) -> dict:
    """Build the terminal episode summary consumed by training callbacks."""
    bs = int(info["blue_score"])
    rs = int(info["red_score"])
    okind = str(info["opponent_kind"]).lower()
    okey = str(info["opponent_key"] or "")
    osnap = okey if okind == "snapshot" else ""
    return {
        "blue_score": bs,
        "red_score": rs,
        "success": 1 if bs > rs else 0,
        "opponent_kind": okind,
        "opponent_snapshot": osnap,
        "scripted_tag": okey if okind == "scripted" else "",
        "species_tag": "BALANCED",
        "map_layout": str(info.get("map_layout", "map_a_open")),
        "map_vertical_mirror": int(bool(info.get("map_vertical_mirror", False))),
        "collisions_per_episode": int(info["collision_events_per_episode"]),
        "collision_events_per_episode": int(info["collision_events_per_episode"]),
        "obstacle_collision_events_per_episode": int(info.get("obstacle_collision_events_per_episode", 0)),
        "collision_free_episode": int(info["collision_free_episode"]),
        "near_misses_per_episode": int(info["near_misses_per_episode"]),
        "navigation_telemetry_version": str(info.get("navigation_telemetry_version", "")),
        "navigation_telemetry_scope": str(info.get("navigation_telemetry_scope", "")),
        "route_classifier_version": str(info.get("route_classifier_version", "")),
        "map_route_metadata_version": str(info.get("map_route_metadata_version", "")),
        "route_telemetry_available": int(bool(info.get("route_telemetry_available", False))),
        "stuck_epsilon": float(info.get("stuck_epsilon", 0.0)),
        "stuck_consecutive_step_window": int(info.get("stuck_consecutive_step_window", 0)),
        "blocked_displacement_threshold": float(info.get("blocked_displacement_threshold", 0.0)),
        "blue_obstacle_collision_events": int(info.get("blue_obstacle_collision_events", 0)),
        "red_obstacle_collision_events": int(info.get("red_obstacle_collision_events", 0)),
        "blue_blocked_movement_events": int(info.get("blue_blocked_movement_events", 0)),
        "red_blocked_movement_events": int(info.get("red_blocked_movement_events", 0)),
        "blue_stuck_steps": int(info.get("blue_stuck_steps", 0)),
        "red_stuck_steps": int(info.get("red_stuck_steps", 0)),
        "blue_repeated_blocked_movement_events": int(info.get("blue_repeated_blocked_movement_events", 0)),
        "red_repeated_blocked_movement_events": int(info.get("red_repeated_blocked_movement_events", 0)),
        "blue_upper_lane_steps": int(info.get("blue_upper_lane_steps", 0)),
        "blue_lower_lane_steps": int(info.get("blue_lower_lane_steps", 0)),
        "blue_neutral_lane_steps": int(info.get("blue_neutral_lane_steps", 0)),
        "red_upper_lane_steps": int(info.get("red_upper_lane_steps", 0)),
        "red_lower_lane_steps": int(info.get("red_lower_lane_steps", 0)),
        "red_neutral_lane_steps": int(info.get("red_neutral_lane_steps", 0)),
        "blue_route_switches": int(info.get("blue_route_switches", 0)),
        "red_route_switches": int(info.get("red_route_switches", 0)),
        "blue_movement_attempts": int(info.get("blue_movement_attempts", 0)),
        "red_movement_attempts": int(info.get("red_movement_attempts", 0)),
        "blue_successful_movement_steps": int(info.get("blue_successful_movement_steps", 0)),
        "red_successful_movement_steps": int(info.get("red_successful_movement_steps", 0)),
        "blue_route_upper_crossings": int(info.get("blue_route_upper_crossings", 0)),
        "blue_route_lower_crossings": int(info.get("blue_route_lower_crossings", 0)),
        "red_route_upper_crossings": int(info.get("red_route_upper_crossings", 0)),
        "red_route_lower_crossings": int(info.get("red_route_lower_crossings", 0)),
        "blue_attack_upper_crossings": int(info.get("blue_attack_upper_crossings", 0)),
        "blue_attack_lower_crossings": int(info.get("blue_attack_lower_crossings", 0)),
        "blue_return_upper_crossings": int(info.get("blue_return_upper_crossings", 0)),
        "blue_return_lower_crossings": int(info.get("blue_return_lower_crossings", 0)),
        "blue_intercept_upper_crossings": int(info.get("blue_intercept_upper_crossings", 0)),
        "blue_intercept_lower_crossings": int(info.get("blue_intercept_lower_crossings", 0)),
        "red_attack_upper_crossings": int(info.get("red_attack_upper_crossings", 0)),
        "red_attack_lower_crossings": int(info.get("red_attack_lower_crossings", 0)),
        "red_return_upper_crossings": int(info.get("red_return_upper_crossings", 0)),
        "red_return_lower_crossings": int(info.get("red_return_lower_crossings", 0)),
        "red_intercept_upper_crossings": int(info.get("red_intercept_upper_crossings", 0)),
        "red_intercept_lower_crossings": int(info.get("red_intercept_lower_crossings", 0)),
        "zone_coverage": float(info["zone_coverage"]),
        "time_to_first_score": info["time_to_first_score"],
        "mean_inter_robot_dist": info["mean_inter_robot_dist"],
        "reward_terminal": float(info["reward_terminal"]),
        "reward_offense": float(info["reward_offense"]),
        "reward_pbrs": float(info["reward_pbrs"]),
        "reward_team": float(info["reward_team"]),
        "reward_sparse": float(info["reward_sparse"]),
        "reward_failure": float(info["reward_failure"]),
        "reward_sparse_points": float(info["reward_sparse_points"]),
        "reward_total": float(info["reward_total"]),
        "decision_steps": int(info["decision_steps"]),
        "vec_schema_version": 1,
    }


__all__ = ["_build_episode_result_payload"]
